export const purityQuestions = [
  // General NYU questions
  "Have you ever been late to class because the subway broke down?",
  "Have you ever had to sprint between Washington Square and Brooklyn campus?",
  "Have you ever been inside Bobst Library past 2 AM?",
  "Have you ever studied in Bobst for more than 8 hours straight?",
  "Have you ever fallen asleep in Bobst?",
  "Have you ever eaten at Palladium past midnight?",
  "Have you ever participated in any NYU protest or rally?",
  "Have you ever taken a class at a different NYU school than your own?",
  "Have you ever attended an NYU athletic event?",
  "Have you ever taken the NYU bus to Brooklyn?",

  // NYU Housing
  "Have you ever snuck someone into your NYU dorm?",
  "Have you ever been written up by an RA?",
  "Have you ever had to deal with NYU Housing for maintenance issues?",
  "Have you ever had a party in an NYU dorm?",
  "Have you ever been caught with alcohol in an NYU dorm?",
  "Have you ever had a roommate conflict so bad that you had to involve an RA?",
  "Have you ever lived in Rubin Hall?",
  "Have you ever lived in Third North?",
  "Have you ever lived in a NYU dorm without AC?",
  "Have you ever taken a nap in a dorm that wasn't yours?",

  // NYU Social Life
  "Have you ever gone to a party at an NYU frat/sorority?",
  "Have you ever joined a club and then never attended meetings?",
  "Have you ever attended Club Fest and signed up for 10+ clubs?",
  "Have you ever developed feelings for someone in your NYU class?",
  "Have you ever hooked up with someone from your NYU class?",
  "Have you ever hooked up with someone from your NYU dorm?",
  "Have you ever asked someone on a date to the Washington Square Arch?",
  "Have you ever gone on more than 3 Tinder/Bumble/Hinge dates in one week?",
  "Have you ever been to an NYU club event just for the free food?",
  "Have you ever been to an NYU networking event just for the free alcohol?",

  // NYC Experiences
  "Have you ever taken the subway in the wrong direction for more than 3 stops?",
  "Have you ever seen a rat in the subway and didn't flinch?",
  "Have you ever seen someone pee on the subway?",
  "Have you ever helped a tourist with directions while knowing you were wrong?",
  "Have you ever pretended to be a native New Yorker?",
  "Have you ever spent more than $20 on a single cocktail?",
  "Have you ever waited in line for more than an hour for a trendy restaurant?",
  "Have you ever walked across the Brooklyn Bridge?",
  "Have you ever been to the top of the Empire State Building?",
  "Have you ever been yelled at by a New Yorker?",

  // NYC Nightlife
  "Have you ever been to a club in the Meatpacking District?",
  "Have you ever been to a rooftop bar in NYC?",
  "Have you ever been to a speakeasy in NYC?",
  "Have you ever been to a warehouse party in Brooklyn?",
  "Have you ever stayed out until sunrise in NYC?",
  "Have you ever been rejected from a club in NYC?",
  "Have you ever paid for bottle service in NYC?",
  "Have you ever been to a celebrity-filled party in NYC?",
  "Have you ever been to a party in a penthouse?",
  "Have you ever bar hopped to more than 5 places in one night?",

  // Food and Drink
  "Have you ever spent more than $100 on a meal in NYC?",
  "Have you ever eaten a $1 pizza slice after 2 AM?",
  "Have you ever stood in line for more than 30 minutes for a cronut/cookie/trendy dessert?",
  "Have you ever been to Smorgasburg?",
  "Have you ever been to Chelsea Market?",
  "Have you ever eaten at a halal cart more than once in a week?",
  "Have you ever tried a chopped cheese?",
  "Have you ever been to Katz's Deli?",
  "Have you ever been to Joe's Pizza?",
  "Have you ever eaten at a Michelin-starred restaurant in NYC?",

  // Transportation
  "Have you ever taken a yellow cab during surge pricing when the subway was an option?",
  "Have you ever fallen asleep on the subway and missed your stop?",
  "Have you ever seen a showtime performance on the subway?",
  "Have you ever given money to a subway performer?",
  "Have you ever biked around Manhattan?",
  "Have you ever taken a helicopter tour of NYC?",
  "Have you ever taken the Staten Island Ferry?",
  "Have you ever been on the Roosevelt Island Tram?",
  "Have you ever taken an Uber Pool with someone strange?",
  "Have you ever been in a Brooklyn vs. Manhattan argument?",

  // Academics
  "Have you ever skipped more than a week of classes?",
  "Have you ever pulled an all-nighter for a paper/exam?",
  "Have you ever used ChatGPT to write a paper?",
  "Have you ever had a class with a famous professor?",
  "Have you ever fallen asleep during a lecture?",
  "Have you ever changed your major more than once?",
  "Have you ever taken a class pass/fail because you were doing poorly?",
  "Have you ever had a celebrity guest speaker in class?",
  "Have you ever taken more than 18 credits in a semester?",
  "Have you ever submitted an assignment one minute before the deadline?",

  // Miscellaneous NYC
  "Have you ever been to all five boroughs?",
  "Have you ever been to a sample sale?",
  "Have you ever seen a celebrity in NYC and pretended not to notice?",
  "Have you ever bought a knockoff handbag/watch in Chinatown?",
  "Have you ever gone ice skating at Rockefeller Center?",
  "Have you ever been to a Broadway show?",
  "Have you ever been to a museum in NYC just for Instagram photos?",
  "Have you ever gotten lost in Central Park?",
  "Have you ever been to Times Square on New Year's Eve?",
  "Have you ever sworn you'd leave NYC, but know you never will?",
];
