export const purityQuestions = [
  // General NYU questions
  "Attended the Strawberry Festival?",
  "Participated in Welcome Week events?",
  "Been to the Presidential Welcome at Radio City Music Hall?",
  "Attended a Violet 100 concert?",
  "Danced at the Violet Ball in Bobst Library?",
  "Taken a class with a professor who appeared on TV or in a movie?",
  "Participated in a research project that was published?",
  "Pulled an all-nighter in Bobst Library?",
  "Fallen asleep during a lecture?",
  "Argued with a professor over a grade?",

  // NYU Housing
  "Switched majors more than once?",
  "Lived in Third North and attended a party there?",
  "Eaten at the Third North dining hall and regretted it?",
  "Been part of a themed floor in Goddard Hall?",
  "Walked from UHall to class in less than 10 minutes?",
  "Worked out at the Palladium gym?",
  "Joined a club or organization on campus?",
  "Held a leadership position in a club?",
  "Participated in a campus-wide event like a concert or festival?",
  "Attended a guest lecture or speaker series?",

  // NYU Social Life
  "Been to a career fair on campus?",
  "Gotten a job or internship from a career fair?",
  "Attended a Broadway show using student discounts?",
  "Visited the Met Museum for free with your NYU ID?",
  "Taken a photo under the Washington Square Arch?",
  "Dipped your feet in the Washington Square Park fountain?",
  "Seen a celebrity on the street in NYC?",
  "Been to a rooftop bar in Manhattan?",
  "Had a picnic in Central Park?",
  "Gone to a comedy club in the Village?",

  // NYC Experiences
  "Attended a film screening at Tisch?",
  "Seen a classmate's art exhibition?",
  "Taken the wrong subway line and ended up in a different borough?",
  "Been on a subway car with a performer or a preacher?",
  "Missed your stop because you were too engrossed in your phone?",
  "Jaywalked in front of a cop?",
  "Gotten lost in the city and had to ask for directions?",
  "Experienced a NYC blackout?",
  "Been stuck in traffic on the way to class?",
  "Taken a cab or Uber because you were late?",

  // NYC Nightlife
  "Studied at one of NYU's global sites?",
  "Participated in a short-term study away program?",
  "Made friends with students from NYU's global campuses?",
  "Held hands with someone on campus?",
  "Kissed someone in Washington Square Park?",
  "Hooked up in a dorm room?",
  "Had a one-night stand with someone you met at an NYU party?",
  "Sent a risky text to someone in your class?",
  "Matched with someone from NYU on a dating app?",
  "Gone on a date with someone you met online?",

  // Food and Drink
  "Been in a relationship with someone from a different NYU school?",
  "Had a crush on a TA or professor?",
  "Attended a party where you didn't know anyone?",
  "Thrown up from drinking too much at a party?",
  "Blacked out from drinking?",
  "Smoked weed on campus?",
  "Done harder drugs?",
  "Rushed for a fraternity or sorority?",
  "Attended a Greek life event?",
  "Eaten dumplings at Vanessa's?",

  // Transportation
  "Tried the birria tacos at Birria LES?",
  "Had takoyaki from Otafuku?",
  "Gone to San Marzano for bottomless mimosas?",
  "Eaten from the Halal Guys cart?",
  "Taken the NYU shuttle bus?",
  "Ridden a Citibike to class?",
  "Walked to class in the rain without an umbrella?",
  "Visited the NYU health center?",
  "Attended a yoga class on campus?",
  "Participated in a mental health workshop?",

  // Academics
  "Posted on the NYU Memes for Slightly Bankrupt Teens page?",
  "Gone viral on TikTok for something related to NYU?",
  "Used the NYU Wi-Fi and complained about it?",
  "Maxed out your dining dollars before the end of the semester?",
  "Sold textbooks to afford rent?",
  "Worked a part-time job in the city?",
  "Attended a protest or rally in NYC?",
  "Volunteered for a community service project through NYU?",
  "Visited all five boroughs of NYC?",
  "Seen a movie at the Angelika Film Center?",

  // Miscellaneous NYC
  "Gone to a concert at Webster Hall?",
  "Attended a comedy show at the Comedy Cellar?",
  "Shopped at the Strand Bookstore?",
  "Bought vintage clothing in the East Village?",
  "Splurged on something at SoHo?",
  "Ice skated at Rockefeller Center?",
  "Seen the Macy's Thanksgiving Day Parade in person?",
  "Celebrated New Year's Eve in Times Square?",
  "Attended a lecture by a Nobel laureate at NYU?",
  "Participated in the Reality Show during Welcome Week?",

  // Additional Social and Raunchy Experiences
  "Been to a Drag Bingo event?",
  "Partied until sunrise in the city?",
  "Made out with someone in a club in Meatpacking District?",
  "Had a walk of shame from a dorm?",
  "Hooked up with someone from a different country?",
  "Attended a sex-positive workshop or event?",
  "Attended a burlesque show or performance art event?",
  "Had a romantic encounter in a NYU elevator?",
  "Crashed a party at another university in NYC?",
  "Gone on a class field trip to a museum or gallery?",
];
