// questions.ts

export const purityQuestions = [
  // 1-30: Normalish NYU Life
  "Changed majors more than once?",
  "Been to an NYU sports game?",
  "Lied about your major to someone?",
  "Got rejected by a Stern Club?",
  "Lost your NYU ID?",
  "Bought a fake ID and never got it?",
  "Stayed inside during a fire drill?",
  "Used NYU SafeRide?",
  "Slept at Bobst?",
  "Sexted during a lecture?",
  "Dated someone you met on a dating app?",
  "Worked a shady gig from the NYU Handshake?",
  "Attended a career fair and left with nothing?",
  "Skipped a lecture to sleep off a hangover?",
  "Turned in a paper at 11:59pm?",
  "Failed a midterm after going out the night before?",
  "Vaped during a class?",
  "Been posted on @nyumissedshots?",
  "Had your first kiss with someone from a dating app?",
  "Received a complaint from an RA?",
  "Received a second RA complaint for the same party?",
  "Made out in a dorm common room?",
  "Hooked up with someone you met on the NYU shuttle?",
  "Ghosted someone you met on a dating app?",
  "Gotten an internship through nepotism?",
  "Got serenaded by someone at Washington Square Park?",
  "Made out with someone from the Wrestling Team?",
  "Lost your virginity with someone from a dating app?",
  "Got pitched a pyramid scheme by an AkPsi kid?",
  "Had more than 20 people in your dorm room at once?",
  "Been to a darty at AEPI?",

  // 31-60: Reckless Chaos
  "Smoked in the stairwell of a dorm?",
  "Smoked in Carlyle Court's yard?",
  "Smoked in a bathroom at Bobst?",
  "Did shots at a Lipton pregame till you puked?",
  "Citibiked while drunk?",
  "Hooked up in a dorm's laundry room?",
  "Hooked up in the Weinstein communal shower?",
  "Been on the rooftop of an NYU building?",
  "Had more than 30 people in your dorm room at once?",
  "Gotten a noise violation from a Brittany rager?",
  "Fucked someone in the Bobst stacks after hours?",
  "Received disciplinary action from an RA/housing department?",
  "Made out with a rando at a Palladium foam party?",
  "Kicked out of a building by Campus Safety?",
  "Got interviewed at Washington Square Park for an IG Reel/TikTok?",
  "Took stimulants to study for a test?",
  "Bullied by someone in APHI—or clocked them before they bragged?",
  "Been to a bottle service night with Stern kids?",
  "Gotten into The Box with a fake ID?",
  "Hooked up with someone from another NYU campus (e.g., Brooklyn)?",
  "Had your valuables stolen at a dorm party?",
  "Went to Santacon and regretted it?",
  "Hooked up with someone you met at a Zeta Psi darty?",
  "Was not so sober at a sober sister event?",
  "Been to Wonderland?",
  "Done coke at The Playground?",
  "Smoked in a dorm and set off the alarm?",
  "Got rejected by a Wash Square Park guitarist after a bad pickup line?",

  // 61-80: Wild Shit and WTF Territory
  "Did Molly at a party?",
  "Blacked out at a dorm and woke up in the lounge?",
  "Fucked someone in a bathroom during a club event?",
  "Had sex in a lecture hall after hours?",
  "Hooked up with a TA in their office?",
  "Hooked up with someone from each NYU college?",
  "Spotted Lady Gaga in NYC?",
  "Had more than 40 people in your dorm room at once?",
  "Hooked up with ten people in one night?",
  "Crashed a billionaire's after-party?",
  "Got caught sneaking into a Sternie's party?",
  "Banged someone you met at a Kimmel event?",
  "Did cocaine in a Third North bathroom?",
  "Hooked up with a rando from a dating app in Bobst?",
  "Fucked someone in a dorm living room while their roommate was home?",
  "Had a threesome?",
  "Pissed between subway cars?",
  "Been Roofied at a DKE party?",
  "Banned from an NYU building?",
  "Had to switch housing after a 50-person party?",
  "Snorted coke during finals week?",
  "Had sex with a professor?",
  "Used your roommate's clothes as a towel after a hookup?",
  "Banged a Stern kid in their room while their roommate slept?",
  "Got arrested from a club night that went sideways?",
  "Fucked someone in the Palladium pool after hours?",
  "Saw Timothée Chalamet at Washington Square?",

  // to check:
  "Been in the elevator while people were making out?",
  "Been to a frat at columbia?",
  "Been hit on in the elevator?",
  "Had someone buy you drinks then ditch them?",
  "been to poco thursday?",
  "Spent 4/20 at Washington Square Park?",
  "Jumped a turnstile and got caught?",
  "Recieved a UTI from a one-night stand?",
  "Met someone from Gallatin with a weird major?",
  "Took the virginity of a guy at Tandon?",

  "Took a CAMS class which made you reconsider your life?",
  "Had a horrible freshman year roommate?",
  "Lost touch with your welcome week friends?",
  "Took a plan B?",
];
